clone_folder: "c:\\WORK"
clone_depth: 5

# Do not build feature branch with open Pull Requests
skip_branch_with_pr: true

platform:
  - x86_64

cache:
  - "C:\\SR"
  - dist-newstyle

environment:
  global:
    CABOPTS: --store-dir=C:\\SR

  matrix:
    - GHCVER: 8.8.1

install:
  - choco source add -n mistuke -s https://www.myget.org/F/mistuke/api/v2
  - choco install -y cabal --version 3.0.0.0
  - choco install -y ghc   --version 8.8.1
  - refreshenv

before_build:
  - cabal --version
  - ghc   --version
  - cabal %CABOPTS% update

build_script:
  - cabal %CABOPTS% build all --enable-tests
  - cabal %CABOPTS% test  all --enable-tests
