resolver: nightly-2019-05-01

packages:
  - co-log-core
  - co-log
  - co-log-polysemy
  - co-log-benchmark

extra-deps:
  - polysemy-0.3.0.0 
  - typerep-map-0.3.2
  - th-abstraction-0.3.1.0
  - aeson-1.4.3.0
